#!/usr/bin/env python3
"""Generates references/metric-sector-catalog.md from the vendored Malachite data.

The catalog is the agent-readable source for every metric slot in the generic
templates (event filter, observed value, metric argument, entity fields). Hunts
cannot run Python, so the agent reads this file instead of calling the router.

Usage:
  python3 -m scripts.generate_metric_sector_catalog           # rewrite the file
  python3 -m scripts.generate_metric_sector_catalog --check   # exit 1 on drift

Author: Greg Kushmerek
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
  from . import malachite_catalog as mc
except ImportError:  # executed as a plain script
  sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
  from scripts import malachite_catalog as mc  # type: ignore

OUTPUT_PATH = mc.SKILL_ROOT / "references" / "metric-sector-catalog.md"

HEADER = """\
# Metric Sector Catalog (generated)

<!-- GENERATED by scripts/generate_metric_sector_catalog.py from data/malachite/*.textproto and
     data/metric_baseline_semantics.json. Do not edit by hand; regenerate. -->

This file supplies every metric-specific slot in the generic templates
(`templates/pipelines/dual_sector_fusion_3stage.yl2`, `multi_sector_fusion_4stage.yl2`,
`rollup_sector_fusion_4stage.yl2`, `rollup_sector_fusion_5stage.yl2`, and the event filter / observed
value / entity field slots of the other pipelines). Source of truth:
the compiler's own `config.textproto` (valid dimension sets) and `dimension_field_mapping.textproto`
(dimension → UDM fields), plus our restatement of each metric's baseline SQL.

## How to use a row

* **Observed event filter**: paste every line into the stage's event section, one per line. These
  lines select the same events the 30-day baseline counts, so observed and baseline are comparable.
  Do not substitute a `metadata.event_type` guess; several baselines (DNS, HTTP, network, alerts,
  workspace) do not filter on event type at all.
* **Observed value**: the stage outcome expression for today's value (`$obs = <value>`).
* **Metric arg**: the `metric:` argument of the `metrics.<name>(...)` call.
* **Entity identifier fields**: fields that may appear *alone* as the metric's filter (one valid
  single-dimension set). Bind the same field in the event section (`<field> = $entity`) and in the
  metric call (`<field>: $entity`). Defaults: `userid` for users, `hostname` for devices.
* **Composite-only** metrics have no single-field set. Every call must supply one complete valid
  dimension set (listed in the row). They become fusion sectors only as a **roll-up sector** (below).
* **Roll-up sector sets** (composite-only rows): each block is one valid set with exactly one entity
  dimension. Fill `rollup_sector_fusion_4stage.yl2` / `_5stage.yl2` sector A from it: the detail stage
  binds the entity plus every companion (*Detail bindings*), matches on *Match keys*, and passes
  *Metric filters* to every `metrics.<name>(...)` call; the roll-up stage counts distinct *Distinct key*.

## The exact-set rule (compiler)

The compiler maps every filter argument of a `metrics.*()` call to its dimension and requires the
resulting *set* to equal one valid set exactly (`ueba_validator.go`). Adding a field that is valid
elsewhere still fails if the combined set is not listed. Example: `auth_attempts_fail` accepts
`principal.asset.hostname` + `target.user.userid` but rejects `principal.asset.hostname` +
`target.asset.hostname`.

## Fusion pairing rules (`dual_sector_fusion_3stage`, `multi_sector_fusion_4stage`, `rollup_sector_fusion_*`)

1. Same entity kind on both sides: user ↔ user or device ↔ device. Never user ↔ host.
2. Same identifier on both sides: userid ↔ userid, hostname ↔ hostname, email_addresses ↔
   email_addresses. Principal vs. target does not matter (`target.user.userid` joins
   `principal.user.userid`).
3. Each sector's entity field must be listed below for its metric.
4. A composite-only metric (e.g. `file_executions_*`, so process execution + DNS) can be a sector only as a
   roll-up sector in `rollup_sector_fusion_4stage.yl2` (or `_5stage.yl2` with fleet normalization), and at
   most one sector per query may be a roll-up. Its Z is the largest per-key Z for the entity (per binary,
   product or rule), not a Z of the entity's total volume: no entity-only baseline exists. Add an
   `// ADVISORY:` line saying so. Its entity must be the only entity dimension of one listed roll-up set.
5. Two metrics of the same family (e.g. `auth_attempts_fail` + `auth_attempts_total`) are allowed but
   correlated; add an `// ADVISORY:` line to the query header saying so.
6. `email_addresses`, `ip` and `mac` are repeated fields: one event can fan out to several entities.

"""


def _entity_lines(metric: str) -> list[str]:
  out = []
  fields = mc.dimension_fields()
  for dim in sorted(mc.entity_only_dimensions(metric)):
    kind = "user" if dim in mc.USER_DIMENSIONS else "device"
    listed = ", ".join(f"`{f}`" for f in fields[dim])
    out.append(f"  * {dim} ({kind}): {listed}")
  return out


def _default_field(dim: str) -> str:
  leaf = mc.DEFAULT_USER_IDENTIFIER if dim in mc.USER_DIMENSIONS else mc.DEFAULT_DEVICE_IDENTIFIER
  return next(f for f in mc.dimension_fields()[dim] if f.endswith("." + leaf))


def _rollup_lines(metric: str) -> list[str]:
  """Roll-up sector sets: one block per valid set whose only entity dimension is a user or device."""
  fields = mc.dimension_fields()
  out = ["* **Roll-up sector sets** (sector A of `rollup_sector_fusion_*`; smallest set per entity dimension. Any "
         "other set above with exactly one user/device dimension works the same way: bind every other dimension):"]
  found = False
  for dim in sorted(mc.ENTITY_DIMENSIONS):
    for st in mc.rollup_dimension_sets(metric, dim)[:1]:
      found = True
      companions = sorted(st - {dim})
      plan = mc.rollup_plan(metric, fields[dim][0], companions)
      kind = "user" if dim in mc.USER_DIMENSIONS else "device"
      out.append(f"  * **{dim}** ({kind}) + {' + '.join(companions)}")
      out.append(f"    * Entity field: any {dim} field (see *Dimension → UDM fields*); default `{_default_field(dim)}`")
      out.append("    * Detail bindings: " + "; ".join(f"`{b}`" for b in plan.companion_bindings()))
      out.append(f"    * Match keys: `{plan.match_keys()}`")
      out.append(f"    * Metric filters: `{plan.metric_filters().replace(fields[dim][0], '<entity field>', 1)}`")
      out.append(f"    * Distinct key: `{mc.companion_var(plan.detail_key_dimension).lstrip('$')}`")
  if not found:
    out.append("  * none (no valid set has exactly one user/device dimension)")
  return out


def _row(metric: str) -> str:
  sem = mc.baseline_semantics(metric)
  lines = [f"### `metrics.{metric}`", ""]
  lines.append(f"* **Family**: {mc.metric_family(metric)}")
  lines.append(f"* **Baseline counts**: {sem.baseline_sql_where}")
  lines.append("* **Observed event filter**:")
  lines.append("  ```yara")
  lines.extend(f"  {ln}" for ln in sem.observed_filter)
  lines.append("  ```")
  lines.append(f"* **Observed value**: `{sem.observed_agg}`")
  lines.append(f"* **Metric arg**: `metric: {sem.metric_arg}`")
  if mc.is_composite_only(metric):
    lines.append("* **Composite-only**: yes. Every call needs one complete valid set:")
    for s in mc.valid_dimension_sets_text(metric):
      lines.append(f"  * {s}")
    lines.extend(_rollup_lines(metric))
  else:
    lines.append("* **Entity identifier fields** (valid alone):")
    lines.extend(_entity_lines(metric))
    others = [s for s in mc.valid_dimension_sets_text(metric) if "+" in s]
    if others:
      lines.append("* **Other valid dimension sets**: " + "; ".join(others))
  for note in sem.notes:
    lines.append(f"* **Note**: {note}")
  lines.append("")
  return "\n".join(lines)


def _dimension_legend() -> str:
  used = sorted({d for m in mc.known_metrics() for s in mc.metric_dimension_sets()[m] for d in s})
  fields = mc.dimension_fields()
  lines = ["## Dimension → UDM fields", "", "| Dimension | UDM fields |", "| :--- | :--- |"]
  for d in used:
    lines.append(f"| {d} | " + ", ".join(f"`{f}`" for f in fields.get(d, ())) + " |")
  lines.append("")
  return "\n".join(lines)


TRIAD_RULES = """\
## Sibling triads (`part_of_the_whole_triad_multilevel.yl2`)

One stage (`all_entities`) observes three sibling metrics for the same entity, then compares each
against the personal 30-day baseline and the fleet (enterprise). A team cohort stage is optional: keep
the template's `// >>> TEAM COHORT` blocks only when the analyst names a peer group; with no peer list
it would just recompute the fleet, so delete them and rank by `$d_vs_fleet_sq`. Because one stage
carries all three metrics:

1. **One entity field for all three.** It must be valid alone for every metric (listed per triad).
   Bind it once: `<entity field> = $user` (or `$host`) in the stage and `<entity field>: $user` in all
   six `metrics.*()` calls.
2. **Stage filter = the union, not any one metric's filter.** Paste the triad's *Stage event filter*
   lines into the `event_filter` slot. Never add one metric's own extra line (e.g.
   `security_result.action = "ALLOW"`) to the stage: it zeroes the sibling counts.
3. **Observed values.** Use the triad's *Observed values*: counts whose metric adds a filter line are
   conditional sums over that line, so each observed value counts the same events as its baseline.
   Fail + success = total (verified live: Administrator 6241 = 6171 fail + 70 success; DNS on
   mikeross-pc 4 = 3 + 1). Outbound and inbound overlap: a flow with both sent and received bytes counts
   in both, so outbound + inbound can exceed total.
4. **Only the triads below.** Composite-only families (`file_executions_*`, `resource_*`,
   `alert_event_name_count`) cannot form a triad: the stage matches the entity alone and those metrics
   have no entity-only baseline. For process execution use a per-(host, hash) pipeline or a roll-up
   sector. Do not mix families into a triad (e.g. `dns_bytes_outbound` with DNS query counts: it counts
   port-53 traffic, not DNS messages); use a sector fusion instead.
5. **Math (as the template computes it).** Per metric: $Z_{personal}$ and $Z_{vs\\_enterprise}$ (plus
   $Z_{vs\\_team}$ with a peer group). Composite: $D_{vs\\_fleet}^2 = \\sum_{m=1}^{3} Z_{vs\\_enterprise,m}^2$
   ($D_{vs\\_team}^2$ likewise with a peer group). The terms are **two-sided**, so a collapse (e.g.
   success drops while fail rises) also raises $D$. To score surges only, rectify each term in the root
   outcome: `$z1_sq = if($z1_vs_enterprise > 0, $z1_vs_enterprise * $z1_vs_enterprise, 0)`.
6. Byte triads observe `sum(network.sent_bytes)` / `sum(network.received_bytes)` over the union of
   rows; the per-metric `< 1000000000000000` guard is not applied per metric, so a single corrupt
   row (>= 1e15 bytes) can inflate one observed value.
"""


def _triad_section() -> str:
  parts = [TRIAD_RULES]
  for label, metrics in mc.CANONICAL_TRIADS:
    stage_filter, observed = mc.triad_event_selection(metrics)
    dims = mc.triad_entity_dimensions(metrics)
    lines = [f"### {label} triad", ""]
    lines.append("* **Metrics (m1, m2, m3)**: " + ", ".join(f"`{m}`" for m in metrics))
    ents = []
    for d in dims:
      kind = "user" if d in mc.USER_DIMENSIONS else "device"
      ents.append(f"{d} ({kind}, default `{_default_field(d)}`)")
    lines.append("* **Entity dimensions valid for all three**: " + "; ".join(ents)
                 + ". Any field of the chosen dimension works (see *Dimension → UDM fields*).")
    lines.append("* **Stage event filter** (`event_filter` slot):")
    lines.append("  ```yara")
    lines.extend(f"  {ln}" for ln in stage_filter)
    lines.append("  ```")
    lines.append("* **Observed values**:")
    for i, m in enumerate(metrics, 1):
      arg = mc.baseline_semantics(m).metric_arg
      lines.append(f"  * `m{i}_observation_agg` ({m}): `{observed[m]}`; metric arg `metric: {arg}`")
    lines.append("")
    parts.append("\n".join(lines))
  return "\n".join(parts)


def render() -> str:
  metrics = sorted(mc.known_metrics())
  fusable = [m for m in metrics if not mc.is_composite_only(m)]
  composite = [m for m in metrics if mc.is_composite_only(m)]
  parts = [HEADER]
  parts.append("## Index\n")
  parts.append("* **Fusion-capable** (entity field valid alone): " + ", ".join(f"`{m}`" for m in fusable))
  parts.append("* **Composite-only** (fusion sector only as a roll-up): " + ", ".join(f"`{m}`" for m in composite))
  parts.append("* **Sibling triads**: " + ", ".join(label for label, _ in mc.CANONICAL_TRIADS)
               + " (see *Sibling triads* below the metric rows)\n")
  parts.append("## Metrics\n")
  parts.extend(_row(m) for m in metrics)
  parts.append(_triad_section())
  parts.append(_dimension_legend())
  return "\n".join(parts).rstrip() + "\n"


def main(argv=None) -> int:
  ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  ap.add_argument("--check", action="store_true", help="exit 1 if the file is out of date")
  args = ap.parse_args(argv)
  text = render()
  if args.check:
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if current != text:
      print(f"{OUTPUT_PATH} is out of date; run python3 -m scripts.generate_metric_sector_catalog")
      return 1
    print("metric-sector-catalog.md is up to date")
    return 0
  OUTPUT_PATH.write_text(text, encoding="utf-8")
  print(f"wrote {OUTPUT_PATH} ({len(text)} bytes)")
  return 0


if __name__ == "__main__":
  sys.exit(main())
